@startuml balances_deposit
entity balances_deposit {
  + ID [PK]
  --
  current_amount
  deposit_amount
  after_amount
  status
  status_code
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
  --
  + user_id [FK]
  + balances_id [FK]
  + shoes_purchase_id [FK]
}
@enduml