@startuml アカウント残高
entity アカウント残高 {
  + ID [PK]
  --
  + ユーザーID [FK]
  + アカウント引出ID [FK]
  + アカウント入金ID [FK]
  --
  残高 : INT
  ステータス : BOOLEAN
  ステータスコード : VARCHAR(n)
  作成日 : TIMESTAMP
  更新日 : TIMESTAMP
}
@enduml