@startuml アカウント入金
entity アカウント入金 {
  + ID [PK]
  --
  + アカウント残高ID [FK]
  + シューズ買取履歴ID [FK]
  --
  残高 : INT
  買取金額 : INT
  合計後残高 : INT
  ステータス : BOOLEAN
  ステータスコード : VARCHAR(n)
  作成日 : TIMESTAMP
  更新日 : TIMESTAMP
}
@enduml