@startuml クレジットカード
entity クレジットカード {
  + ID [PK]
  --
  ユーザーID [FK]
  --
  ブランド名 : TEXT
  カード番号下4桁 : INT
  有効期限 : INT
  stripeユーザーID : VARCHAR(n)
  ステータス : BOOLEAN
  ステータスコード : VARCHAR(n)
  作成日 : TIMESTAMP
  更新日 : TIMESTAMP
}
@enduml