@startuml 配送先
entity 配送先 {
  + ID [PK]
  --
  + ユーザーID [PK]
  --
  郵便番号 : VARCHAR(n)
  都道府県 : VARCHAR(n)
  市区町村 : VARCHAR(n)
  番地 : VARCHAR(n)
  建物・ビル名 : VARCHAR(n)
  電話番号 : VARCHAR(n)
  配送料金 : INT
  ステータス : BOOLEAN
  ステータスコード : VARCHAR(n)
  作成日 : TIMESTAMP
  更新日 : TIMESTAMP
}
@enduml