@startuml プラン
entity プラン {
  + ID [PK]
  --
  シューズID [FK]
  プランオプションID [FK]
  --
  プラン名 : TEXT
  プラン金額 : INT
  プラン内容01 : TEXT
  プラン内容02 : TEXT
  プラン内容03 : TEXT
  ステータス : BOOLEAN
  ステータスコード : VARCHAR(n)
  作成日 : TIMESTAMP
  更新日 : TIMESTAMP
}
@enduml