@startuml tables
!include users.pu
!include banks.pu
!include creditcards.pu
!include shoes_purchase.pu

companies ||-d-o{ users
companies ||-o{ positions
users ||-l-o| user_profiles
users ||-d-o{ user_subordinate_users
users ||-o{ user_positions
positions ||-o{ user_positions
@enduml