@startuml tables
!include users.pu
!include balances_history.pu
!include balances_deposit.pu
!include balances_withdraw.pu
!include shoes.pu
!include banks.pu
!include creditcards.pu
!include plans.pu
!include plan_options.pu
!include deliveries.pu
!include valuations.pu
!include shoes_history.pu
!include shoes_deposit.pu
!include shoes_return.pu
!include shoes_purchase.pu

ユーザー ||-d-o{ クレジットカード
ユーザー ||-u-o{ 銀行
ユーザー ||-l-o{ アカウント残高
アカウント残高 ||-d-o{ アカウント入金
アカウント残高 ||-u-o{ アカウント引出
' balances_withdraw ||-r-|| banks
アカウント入金 ||-r-o{ シューズ買取履歴
ユーザー ||-r-o{ シューズ
ユーザー ||-r-o{ 配送先
シューズ ||-u-|| プラン
プラン ||-u-|| プランオプション
シューズ ||-d-o| 相場
シューズ ||-r-o{ シューズ履歴
シューズ履歴 ||-u-o{ シューズ預入履歴
シューズ履歴 ||-r-o{ シューズ返却履歴
シューズ返却履歴 ||-u-|| プランオプション
シューズ返却履歴 ||-d-|| 配送先
シューズ履歴 ||-d-o{ シューズ買取履歴
シューズ買取履歴 ||-l-|| 相場
@enduml