@startuml tables
!include users.pu
!include shoes.pu
!include banks.pu
!include creditcards.pu
!include shoes_deposit.pu
!include shoes_return.pu
!include shoes_purchase.pu

users ||-r-o{ creditcards
users ||-l-o{ banks
users ||-d-o{ shoes
shoes ||-l-o{ shoes_deposit
shoes ||-r-o{ shoes_return
shoes ||-d-o{ shoes_purchase
@enduml