@startuml シューズ
entity シューズ {
  + ID [PK]
  --
  + ユーザーID [FK]
  + プランID [FK]
  + シューズ履歴ID [FK]
  + 相場ID [FK]
  --
  シューズ名 : TEXT
  動画URL : VARCHAR(n)
  画像URL : VARCHAR(n)
  シューズメーカー : VARCHAR(n)
  付属品 : BOOLEAN
  シューズ備考 : TEXT
  発売日 : INT
  製造番号 : VARCHAR(n)
  ステータス : BOOLEAN
  ステータスコード : VARCHAR(n)
  作成日 : TIMESTAMP
  更新日 : TIMESTAMP
}
@enduml