@startuml shoes
entity shoes {
  + ID [PK]
  --
  name
  image_url_xx
  maker
  accessories
  remark
  release_date : DATE
  serial_number : VARCHAR(50)
  status : BOOLEAN
  status_code : CHAR(20)
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
  --
  + user_id [FK]
  + plan_id [FK]
  + shoes_history_id [FK]
  + valuation_id [FK]
}
@enduml