@startuml shoes_deposit
entity shoes_deposit {
  + ID [PK]
  --
  status : BOOLEAN
  status_code : CHAR(20)
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
  --
  + user_id [FK]
  + shoes_id [FK]
}
@enduml