@startuml shoes_return
entity shoes_return {
  + ID [PK]
  --
  status : BOOLEAN
  status_code : CHAR()
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
  --
  + user_id [FK]
  + shoes_id [FK]
  + delivery_id [FK]
}
@enduml