@startuml シューズ履歴
entity シューズ履歴 {
  + ID [PK]
  --
  + シューズID [FK]
  + シューズ預入ID [FK]
  + シューズ引出ID [FK]
  + シューズ返却ID [FK]
  --
  ステータス : BOOLEAN
  ステータスコード : VARCHAR(n)
  作成日 : TIMESTAMP
  更新日 : TIMESTAMP
}
@enduml