@startuml シューズ返却履歴
entity シューズ返却履歴 {
  + ID [PK]
  --
  + ユーザーID [FK]
  + 配送ID [FK]
  + プランオプションID [FK]
  --
  ステータス : BOOLEAN
  ステータスコード : VARCHAR(n)
  発送完了日 : DATE
  作成日(依頼日) : TIMESTAMP
  更新日 : TIMESTAMP
}
@enduml