@startuml shoes
class shoes {
  + ID [PK]
  --
  name
  image_url
  maker
  status
  accessories
  remark
  serial_number
  storage_id
  shoes_deposit_id
  shoes_return_id
  shoes_purchase_id
  valuation_id
  status
  status_code
  created_at
  updated_at
}
@enduml