@startuml shoes_action
entity shoes_action {
  + ID [PK]
  --
  status : BOOLEAN
  status_code : CHAR(20)
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
  --
  + shoes_id [FK]
  + shoes_deposit [FK]
  + shoes_return [FK]
  + shoes_purchase [FK]
}
@enduml