@startuml users
entity users {
  + ID [PK]
  --
  name : TEXT()
  name_ruby : TEXT()
  email : VARCHAR(191)
  phone_number : VARCHAR()
  birthday : DATE
  password : VARCHAR(50)
  balance : INTEGER
  status : BOOLEAN
  status_code : CHAR(20)
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
  --
  shoes_id [FK]
  bank_id [FK]
  creditcard_id [FK]
  plan_id [FK]
  stripe_user_id [FK]
  sms_user_id [FK]
}
@enduml