@startuml ユーザー
entity ユーザー {
  + ID [PK]
  --
  シューズID [FK]
  銀行ID [FK]
  クレジットカードID [FK]
  残高ID [FK]
  --
  ユーザー名 : TEXT
  ユーザー名フリガナ : TEXT
  メールアドレス : VARCHAR(n)
  電話番号 : VARCHAR(n)
  生年月日 : DATE
  パスワード : VARCHAR(n)
  ステータス : BOOLEAN
  ステータスコード : VARCHAR(n)
  作成日 : TIMESTAMP
  更新日 : TIMESTAMP
}
@enduml